import { ColorMapping } from '../models/settings.model';

export const DEFAULT_COLOR_MAPPINGS: ColorMapping[] = [
  { type: 'passive-fish', color: '#22C55E' },
  { type: 'aggressive-bluffer', color: '#EF4444' },
  { type: 'lag', color: '#F97316' },
  { type: 'solid-regular', color: '#3B82F6' },
  { type: 'tight-nit', color: '#14B8A6' },
  { type: 'unknown', color: '#6B7280' },
];

export const COLOR_TYPE_LABELS: Record<string, Record<string, string>> = {
  'passive-fish': { es: 'Pez pasivo', en: 'Passive Fish' },
  'aggressive-bluffer': { es: 'Agresivo / Farolero', en: 'Aggressive / Bluffer' },
  lag: { es: 'LAG', en: 'LAG' },
  'solid-regular': { es: 'Regular sólido', en: 'Solid Regular' },
  'tight-nit': { es: 'Ajustado / Nit', en: 'Tight / Nit' },
  unknown: { es: 'Desconocido', en: 'Unknown' },
};

export const AVATAR_EMOJIS = [
  '😎',
  '🤠',
  '🦊',
  '🐺',
  '🦈',
  '🐟',
  '🎭',
  '🃏',
  '👑',
  '💀',
  '🔥',
  '❄️',
  '🌊',
  '⚡',
  '🎯',
  '🎲',
  '🏆',
  '💰',
  '🤑',
  '🧊',
  '🐻',
  '🦁',
  '🐯',
  '🐸',
  '🦅',
  '🦉',
  '🐍',
  '🐊',
  '🕷️',
  '🦂',
  '👻',
  '🤖',
  '👽',
  '🧙',
  '🧛',
  '🥷',
  '🤡',
  '💎',
  '🪙',
  '🎩',
  '🍀',
  '🌶️',
  '🌪️',
  '☠️',
  '🛡️',
  '⚔️',
  '🧠',
  '👁️',
  '🫀',
  '🦷',
];
